PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#>
 
SELECT  ?developmentphase (count (distinct ?chemblcompound) as ?n)
WHERE {
  ?drugindication chembl:hasMeshHeading "Osteoarthritis" ; 
                  chembl:hasMolecule ?chemblcompound .
  ?chemblcompound chembl:highestDevelopmentPhase ?developmentphase .
  VALUES ?developmentphase {1.0 2.0 3.0 4.0}
      		} ORDER BY DESC (?developmentphase)
